// src/app/features/cloud/payloadEncryption.ts
//
// AES-256-GCM payload encryption for cloud backup using expo-crypto.
//
// WHY expo-crypto INSTEAD OF @tetherto/wdk-utils:
//   @tetherto/wdk-utils exports encrypt/decrypt (AES-256-GCM + real scrypt
//   via @noble/ciphers), which would be the natural choice. However wdk-utils
//   is designed to run inside the Bare worklet runtime, not in the React
//   Native JS thread:

//   1. @noble/ciphers calls globalThis.crypto.getRandomValues — this throws
//      "crypto.getRandomValues must be defined" on Android in the RN JS context
//      because the Web Crypto global is not reliably available outside the
//      Bare runtime.

//   2. wdk-utils@1.0.0-beta.9 requires bare-node-runtime@^1.4.0, conflicting
//      with the 1.2.0 pin required to avoid the ADDON_NOT_FOUND worklet bug.

//   expo-crypto is the correct alternative — it uses native JSI (CommonCrypto
//   on iOS, javax.crypto on Android) with no Web Crypto dependency.
//   The WDK itself already uses expo-crypto in mmkvKeyManager.ts.
//
// Key derivation:
//   SHA-512(passphrase + salt) → first 32 bytes → AES-256 key.
//   A 32-byte random salt per backup makes precomputed attacks impossible
//   even with a fast KDF. The passphrase is a developer-set build constant
//   (not a user-typed low-entropy password), so PBKDF2/scrypt iteration
//   counts are not required for security here.
//
//   ⚠️  PRODUCTION NOTE: EXPO_PUBLIC_* values are inlined into the JS bundle.
//   In production, derive the passphrase from a per-user or per-device secret
//   (e.g. a biometric-protected keychain entry), never from a bundled env var.
//
// Security properties:
//   - AES-256-GCM (authenticated encryption — detects any tampering)
//   - SHA-512 key derivation with 32-byte random salt per backup
//   - Random IV generated by aesEncryptAsync internally

import {
  AESEncryptionKey,
  AESSealedData,
  aesEncryptAsync,
  aesDecryptAsync,
  getRandomBytes,
  digestStringAsync,
  CryptoDigestAlgorithm,
  CryptoEncoding,
} from 'expo-crypto';

// ─── Key derivation ───────────────────────────────────────────────────────────
// One SHA-512 call: hash(passphrase + salt) → 64-byte hex → first 32 bytes
// = AES-256 key. Fast (single native call), secure with a 32-byte random salt.

async function deriveKeyHex(passphrase: string, saltHex: string): Promise<string> {
  const hash = await digestStringAsync(
    CryptoDigestAlgorithm.SHA512,
    passphrase + saltHex,
    { encoding: CryptoEncoding.HEX }
  );
  // SHA-512 produces 128 hex chars (64 bytes). Take the first 64 hex chars
  // = 32 bytes = AES-256 key size.
  return hash.slice(0, 64);
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface EncryptedPayload {
  /** Hex-encoded 32-byte random salt */
  salt: string;
  /** Base64-encoded combined IV + ciphertext + GCM tag */
  combined: string;
}

// ─── Encrypt ──────────────────────────────────────────────────────────────────

export async function encryptPayload(
  plaintext: string,
  passphrase: string
): Promise<EncryptedPayload> {
  const saltBytes = getRandomBytes(32);
  const saltHex = bytesToHex(saltBytes);

  const keyHex = await deriveKeyHex(passphrase, saltHex);
  const aesKey = await AESEncryptionKey.import(keyHex, 'hex');

  const encoder = new TextEncoder();
  const sealedData = await aesEncryptAsync(encoder.encode(plaintext), aesKey);

  const combinedBase64 = await sealedData.combined('base64') as string;

  return { salt: saltHex, combined: combinedBase64 };
}

// ─── Decrypt ──────────────────────────────────────────────────────────────────

export async function decryptPayload(
  payload: EncryptedPayload,
  passphrase: string
): Promise<string> {
  const keyHex = await deriveKeyHex(passphrase, payload.salt);
  const aesKey = await AESEncryptionKey.import(keyHex, 'hex');

  // fromCombined requires raw bytes — base64 string fails on Android native bridge
  const combinedBytes = Uint8Array.from(
    atob(payload.combined),
    (c) => c.charCodeAt(0)
  );
  const sealedData = AESSealedData.fromCombined(combinedBytes);

  let decryptedBytes: Uint8Array;
  try {
    decryptedBytes = await aesDecryptAsync(sealedData, aesKey) as Uint8Array;
  } catch {
    throw new Error(
      'Decryption failed. The passphrase may be incorrect, or the ' +
      'backup payload may be corrupted.'
    );
  }

  const decoder = new TextDecoder();
  return decoder.decode(decryptedBytes);
}